### ISSUE TITLE
Mutation operator - cfggp

### ISSUE THREAD

**Issue by alexgcsa** [grantdick/libgges#1]
Hi,

I have a doubt about the mutation operator in the 'cfggp.c' code. 

During breeding (gges_cfggp_breed), you generate a (pseudo-)random real number. Right? 
Basing on this number, you decide if the GGP will perform crossover or mutation (from line 315 to line 333 of 'cfggp.c') .

However, in the mutation function (gges_cfggp_mutation), you test again if GGP is going to perform mutation or not (line 271 of 'cfggp.c'):
"if (rnd() > mutation_rate) return;"

Thus, you are using two numbers to decide the same thing. I believe the probability variable p (defined in the lines 315 and 317 of 'cfggp.c') should be used as a parameter to do what the test in the line 271 is doing. Or even not used, because the test of performing mutation or not is done in the breed function.

This way is decreasing the use of the mutation operator in the code. In other words, you have to set the value of the parameter before running a given experiment, but you are actually using a lower level of mutation.

I might be wrong about it. It just is something I observed when I was using this code.

Thanks and kind regards,

Alex de Sá

**Comment by grantdick** [comment]
Hi Alex,

Yes, this appears to be an oversight and (I’m pretty sure) would have the effect of lowering the mutation rate. Line 271 should be deleted. I suspect that it’s there from an early design decision that we quickly replaced around how mutation and crossover worked in CFG-GP (in the end, we went with the more familiar approach from GP of crossover and mutation being separate operators, not chained operators).

I’ll push a corrected version onto GitHub later today – thanks for pointing this out!

Cheers,
Grant.

**Comment by alexgcsa** [comment]
Hi Grant,

Thanks for answering.

Regards,

Alex de Sá
